### PR TITLE
Luna cycle BBSHD support

### PR DESCRIPTION
**Pull request by nitrousnrg**
Basic support for this controller. More updates to come.

### CODE REVIEW

**Comment by andresv** [comment]
Do you have a link to this controller. Did Luna Cycle build a special VESC controller for BBSHD motor?

**Comment by nitrousnrg** [comment]
Sorry, no info available atm

**Comment by nitrousnrg** [comment]
Branch rebased to latest master branch to fix new merge conflicts

**Comment by nitrousnrg** [comment]
I didn't create the pull request to add VESC Tool support to the new FAULT_CODE_BRK, as its only a 2 line change.
I don't mind creating the PR if you prefer so.

**Pull request merged**
