### PR TITLE
Disable field weakening when erpm < sensorless

### PR DESCRIPTION
**Pull request by surfdado**
Signed-off-by: Dado Mista <dadomista@gmail.com>

### CODE REVIEW

**Comment by vedderb** [comment]
Why would you disable field weakening in the sensored region?

**Comment by Teslafly** [comment]
If the sensored cutoff erpm is increased with a higher speed sensor into the region you want field weakening, this could be problematic. and probably needs more justification and nuance.

**Comment by surfdado** [comment]
The reason I've added this change is that I have personally experienced massive torque loss when going up really steep inclines slowly, so this change fixed that problem for me. If I'm going 2-3mph I just don't see the benefit of having field weakening kick in, just wasn't sure if there was some corner case I wasn't considering

But I have to admit that I was approaching this with a pretty narrow mindset, thinking only about our Onewheel usecases and 2000erpm aka 4mph sensorless transition speed. I didn't necessarily expect this to get accepted into mainline, just wanted feedback to make sure I'm not doing something stupid/dangerous

**Comment by nitrousnrg** [comment]
Big no-no for those using a resolver 100% of the time 🙂
Large inverters usually run 100% sensored and use field weakening.

**Comment by vedderb** [comment]
A better way might be to limit the fw current to sqrt(i_max^2 - iq^2). Then the Q-axis gets priority on the current. I don't want to try that before the release though, so that is for the next beta.

**Pull request closed without merging**
