### PR TITLE
Balance-app: Introduce optional "Reverse-Stop" behavior

### PR DESCRIPTION
**Pull request by surfdado**
This feature, when enabled, allows riders to stop their vehicle by simply riding
in reverse. A minimum forward speed threshold can be configured (via ERPM).

Once the minimum speed threshold is exceeded for the first time the reverse stop
feature will be "armed". Afterwards when the rider comes to a standstill and goes
the slightest bit in reverse the board will stop (triggering a REVERSE_FAULT).

This allows new riders to stop without learning how to heel-lift or
having to jump off.

Signed-off-by: Dado Mista <dadomista@gmail.com>

### CODE REVIEW

**Comment by surfdado** [comment]
Is this how I summon @Mitchlol ? Sorry, still a noob at this...

**Comment by Mitchlol** [comment]
Code looks nice and clean, but i have a few thoughts on functionality improvements, however I've never used a vehicle with this feature enabled (not a fan of the whole concept), so give me some time to experiment and test things and see how it feels.

**Comment by surfdado** [comment]
Sounds good, thanks

**Comment by surfdado** [comment]
There's a better way of doing reverse stop - ignore this one

**Pull request closed without merging**
