### PR TITLE
Pwm&Dir App

### PR DESCRIPTION
**Pull request by adilrepas**
Add Pwm&Dir App

### CODE REVIEW

**Comment by Teslafly** [comment]
What is this merge request for? is there a thread or forum associated with it?
your description is not very helpful.

It also looks like you are merging the dev branch into master. You probably want to be submitting the pull request to the dev branch instead.

**Comment by adilrepas** [comment]
vesc is widely used to control ac servo for direct drive steering wheel, but most software for steering wheel use pwm dir to control driver

**Comment by adilrepas** [comment]
this is an example of a project i'm working on stm32f4 sends pwm dir signal to vesc and vesc as driver to control ac servo i use yaskawa 1.3kw ac servo

https://youtu.be/bZ01E70Ek8o

**Comment by vedderb** [comment]
Can you change the PR to the dev_fw_5_03 branch?

**Pull request closed without merging**
