### PR TITLE
Replace call to qsort with insertionsort

### PR DESCRIPTION
**Pull request by Gamer43**
Small change, probably negligible impact. Should save a few clock cycles :).

### CODE REVIEW

**Comment by kalvdans** [comment]
While you are on to optimizing it, the median can be found in O(n), no need to sort the array.

**Comment by Gamer43** [comment]
> 
> 
> While you are on to optimizing it, the median can be found in O(n), no need to sort the array.

While such algorithms (such as quickselect) have a linear asymptotic running time, they are recursive and have unacceptable overhead computation. As such they are unsuitable for this application. Perhaps if the need were to find the median in one thousand or one million elements, then an alternative algorithm would be more suitable. But, in this application, the number of elements does not exceed 100.

**Comment by kalvdans** [comment]
The call overhead depends on the compiler. Measure, don't assume :)

**Comment by Gamer43** [comment]
> The call overhead depends on the compiler. Tail calls gets converted to a loop. Measure, don't assume :)

You would have to implement that algorithm manually to ensure it uses tail calls and optimizes into an iterative loop. I am also referring to the overhead coefficients that are not present in the asymptotic notation. There is a reason why Insertion Sort beats every other sorting algorithm with arrays smaller than 40 elements. 
If median of medians or quickselect were actually viable algorithms, then we'd be using them for pivot selection in quicksort, except we don't because the overhead terms causes the average and even best case running times to be significantly worse.
Not only that, this is an embedded system that requires minimal resource usage overhead in every respect. Insertion Sort is the lowest overhead implementation of this.

**Comment by Teslafly** [comment]
Is this still relevant?

**Comment by Gamer43** [comment]
> Is this still relevant?

Codebase appears to have diverged quite significantly since opening, and I think any possible benefit would be minimal. 

I will be closing this pull request as it is no longer relevant.

**Pull request closed without merging**
