### PR TITLE
Add unity parallel output config

### PR DESCRIPTION
**Pull request by Teslafly**
Unity never got a parallel hw config .h like stormcore and someone on the discord asked for it.

### CODE REVIEW

**Comment by Teslafly** [comment]
Compilation is not currently working. wants a hw_unity_parallel.c file but can't figure out why.

**Comment by Teslafly** [comment]
got some help from Aeroboticist. needs a "core" fw file structure.

**Comment by vedderb** [comment]
It would be good if someone can try this out before merging it. Would be bad to have a config in the repo that makes the unity catch fire. Dual parallel is quite risky in general as both power stages have to be in perfect sync for it to not short out.

**Comment by Teslafly** [comment]
Am less motivated to try and get this working. closing for now.

**Pull request closed without merging**
