### PR TITLE
Rafe custom features v5

### PR DESCRIPTION
**Pull request by rafeh1**

### CODE REVIEW

**Comment by surfdado** [comment]
What is this about? Would you mind explaining what this pull request contains and why you submitted it this way? I'm not even sure how to review this pull request. Or is this something you discussed with Benjamin offline?

**Comment by rafeh1** [comment]
My branch has 2 functions1.  Vesc nodelock to cellphone.          A. Software lock and unlock from cellphone        B. Auto lock after 2 minutes of inactivity (if enabled) to prevent theft
2. Pedelec pas functions from the 3 pin connector gnd 5v sin.  Allows ebike pedelec option 


The branch is also out of date and needs to be reintegrate with main trunk before it can be pulled into trunk.

Rafe Husain
1.951.732.7233
www.Calibike.com 
 
  On Fri, Oct 7, 2022 at 10:49 PM, ***@***.***> wrote:   


What is this about? Would you mind explaining what this pull request contains and why you submitted it this way? I'm not even sure how to review this pull request. Or is this something you discussed with Benjamin offline?

**Comment by Teslafly** [comment]
should this pull request be closed then? there are 0 files changed.

**Comment by rafeh1** [comment]
In process of testing merge

Rafe Husain
1.951.732.7233
www.Calibike.com 
 
  On Tue, Nov 15, 2022 at 2:50 PM, ***@***.***> wrote:   


should this pull request be closed then? there are 0 files changed.

**Pull request closed without merging**
